apiVersion: v1
kind: Service
metadata:
  labels:
    service: boot-otel-tempo-api
  name: boot-otel-tempo-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    service: boot-otel-tempo-api

