apiVersion: v1
kind: Service
metadata:
  labels:
    service: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 80
  type: ClusterIP
  selector:
    service: pgadmin

