apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: provider1-db-claim
  name: provider1-db-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

