apiVersion: v1
kind: Service
metadata:
  labels:
    service: provider1-db
  name: provider1-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    service: provider1-db
